/*										 | • | ○ | ■ | □ |

☲☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰ Index ☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☲
═══════════════════════════════════════════ Choose INDEX ════════════════════════════════════════════

	• HEAP: Fast inserts (for staging tables)
	• CLUSTERED INDEX: For primary keys (if not, date columns)
	• CLUSTERED INDEX: For non-primary keys (Foreign keys, joins, filters)
	• COLUMNSTORE INDEX: For big analytical queries, reduce the size of large tables
	• FILTER INDEX: Target subset of data. Reduce size of index
	• FILTER INDEX: Enforce Uniqueness. Improve query speed

══════════════════════════════════════════ Monitor Usage ════════════════════════════════════════════	

	• Dynamic Management View (DMV): provides real-time insights about DB peformance and system health

*/
	
sp_helpindex 'Sales.DBCustomers' -- Lists indexes

SELECT 
	tbl.name AS TableName,
	idx.name AS IndexName,
	idx.type_desc AS IndexType,
	idx.is_primary_key AS IsPrimaryKey,
	idx.is_unique AS IsUnique,
	idx.is_disabled AS IsDisabled,
	s.user_seeks AS UserSeeks,
	s.user_scans AS UserScans,
	s.user_lookups AS UserLookups,
	s.user_updates AS UserUpdates,
	COALESCE(s.last_user_seek,s.last_user_scan) LastUpdate
FROM sys.indexes idx
JOIN sys.tables tbl
ON idx.object_id = tbl.object_id
LEFT JOIN sys.dm_db_index_usage_stats S
ON S.index_id = idx.index_id
ORDER BY tbl.name, idx.name

SELECT * FROM sys.tables  -- Tables in the system

SELECT * FROM sys.dm_db_index_usage_stats	-- Statistics of usage DMV

/*
══════════════════════════════════════ Monitor Missing Indexes ══════════════════════════════════════

	• Evaluate the recommendations before creating any index

*/

SELECT * FROM sys.dm_db_missing_index_details

/*
═════════════════════════════════════ Monitor Duplicate Indexes ═════════════════════════════════════
*/

SELECT 
	tbl.name AS TableName,
	col.name AS IndexColumn,
	idx.name AS IndexName,
	idx.type_desc AS IndexType,
	COUNT(*) OVER(PARTITION BY tbl.name, col.name) ColumnCount
FROM sys.indexes idx
JOIN sys.tables tbl ON idx.object_id = tbl.object_id
JOIN sys.index_columns ic ON idx.object_id = ic.object_id AND idx.index_id = ic.index_id
JOIN sys.columns col ON ic.object_id = col.object_id AND ic.column_id = col.column_id
ORDER BY ColumnCount DESC

/*
──────────────────────────────────────── Update statistics ──────────────────────────────────────────
	• When modifying any table, internal DB statistics will not be
*/

SELECT 
	SCHEMA_NAME(t.schema_id) AS SchemaName,
	t.name AS TableName,
	s.name AS StatisticName,
	sp.last_updated AS LastUpdate,
	DATEDIFF(day, sp.last_updated,GETDATE()) AS LastDateUpdate,
	sp.rows AS 'Rows',
	sp.modification_counter AS ModificationsSinceLastUpdate
FROM sys.Stats AS s
JOIN sys.tables t
ON s.object_id = t.object_id
CROSS APPLY sys.dm_db_stats_properties(s.object_id,s.stats_id) AS sp
ORDER BY ModificationsSinceLastUpdate DESC

UPDATE STATISTICS Sales.DBCustomers -- Can be in general o calling the name of a specific StatisticName

EXEC sp_updatestats

/*
────────────────────────────────────────── Fragmentations ───────────────────────────────────────────

	• Unused spaces in data pages, data pages are out of order

	• Methods: 
		○ Reorganize: Defragments leaf nodes to keep them sorted. Light
		○ Rebuild: Recreates index from the scratch. Heavy

	• Syntax: ALTER INDEX index_name ON Schema.TableName REORGANIZE/REBUILD	

	• Actions: <10% No action needed | 10%-30% Reorganize | >30% Rebuild 

*/

SELECT *
FROM sys.dm_db_index_physical_stats (DB_ID(), NULL, NULL, NULL, 'LIMITED')

SELECT 
	tbl.name AS TableName,
	idx.name AS IndexName,
	s.avg_fragmentation_in_percent,
	s.page_count
FROM sys.dm_db_index_physical_stats (DB_ID(), NULL, NULL, NULL, 'LIMITED') as s 
INNER JOIN sys.indexes idx
ON idx.object_id = s.object_id AND idx.index_id = s.index_id
INNER JOIN sys.tables tbl ON idx.object_id = tbl.object_id 
ORDER BY s.avg_fragmentation_in_percent DESC

ALTER INDEX idx_DBCustomers_CS ON Sales.DBCustomers REORGANIZE

ALTER INDEX idx_DBCustomers_CS ON Sales.DBCustomers REBUILD

/*
══════════════════════════════════════════ Execution plan ═══════════════════════════════════════════

		• Roadmap generated by a BD on how it will execute your query step by step
		• Estimated v. Actual Plan --> if they don't match, prolly inaccurate statistics or outdated indexes
		• Types of scans:
			○ Table scan: reads the entire table.
			○ Index scan: scans all data in index to find matches.
			○ Index seek: targeted scan within an index, retreiving only specific rows7

		• Types of joins:
			○ Nested loops: compares tables row by row, best for small tables
			○ Hash match: matches rows using a hash table; best for large tables
			○ Merge join: merge two sorted tables; efficient when both are sorted. 

		• Helps to understand how SQL works behind the scenes, how many resources are used, check if
		  the indexes are being used, and test&experiment with indexes.

──────────────────────────────────────────── SQL Hints ──────────────────────────────────────────────

		• Commands to force the DB to run in a specific way for better performance. 
			○ Test hints in all project environments as performance may vary
			○ Hints are quick fixes, not a permanent solution
*/

SELECT 
	o.Sales,
	c.Country
FROM Sales.Orders o
LEFT JOIN Sales.Customers c WITH (INDEX(PK_customers)) --WITH (FORCESEEK)  
ON o.CustomerID=c.CustomerID 
OPTION(HASH JOIN)